### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by brandenwest** [ajvorobiev/SignForge#1]
These are the steps I took to sign my Pbo's...

Downloaded Signforge...

Put all Pbo's into one folder...

Signed all Pbo's and verified signature check...

Put Pbo's back into respected @Folders with the new bisigns...

Put .Bikey into keys folder...

Put all mods in the Startup command line...

In CONFIG_Vanilla.cfg I put "verifySignatures       = 2;" //No "" were used...

Started server and seen that the keys are not accepted...

I get ...are not signed by a key accepted by this server. To play on this server, remove listed files or install additional accepted keys.

So I'm not sure if I missed something or if I'm doing it wrong... Any help?

**Comment by ajvorobiev** [comment]
Very strange, the keys we generated with this tool for the last RHS release seem to be working fine.

Can someone else confirm this?

**Comment by ace16huey** [comment]
I can but me and op are working on the same project. We have tried like 3 different tools and all have come up with the same results and we don't know if we are missing a step or doing something wrong..I dunno

**Comment by ajvorobiev** [comment]
Hmm the fact that different tools dont work makes me think you guys are doing something wrong serverside.

Lets make sure the setup is right, once all is generated:
1. The `.bikey` file you should put on the server in the `Keys` folder which is in the Arma root.
2. The `.pbo` and `.bisign` files should go in the `arma 3\@youraddon\addons` folder of your server AND every client.
3. The .`biprivatekey` you should keep somewhere safe and SHOULD NOT be distributed.

Anyway, you guys are sure thus far you have been doing it right?

**Comment by ace16huey** [comment]
Yes, I am 99 percent sure that what you stated above has been done correctly.

**Comment by ajvorobiev** [comment]
Ok, but please double check. Also make sure its not some other addon that is there.

**Comment by ace16huey** [comment]
Alrighty, I will get to that as fast as possible

**Comment by ace16huey** [comment]
Sorry that it is taking so long, my upload speed is horrid so it just finished (gotta love 876 kbs -_-) I will get back to you when I get home when I hop In my server again.

**Comment by ace16huey** [comment]
Okay, Well it did not work, I have an error in the A3 master log that is blah blah wrong signature for file then it kicks me

**Comment by ace16huey** [comment]
Just some more info, I wen and put the bikey in my client arma files and turned verify signatures on, It verified them all but 3, this was after we changed our key from all caps to all lowercase, I think that had something to do with the issue as well.

**Comment by ace16huey** [comment]
Actually, you know what? I just found the issue and it was never your fault nor anyone but ourselves... I totally forgot to repack our pbos that we changed textures in through binPbo to update the texHeaders. which is why it would sign but the files would not line up. I am so sorry fro wasting your time sir. I wish you the best of luck. haha

**Comment by brandenwest** [comment]
Thanks for the help...
